# Generated by Django 2.1.7 on 2019-05-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('produtos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='clientes_app.Cliente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='produtos_app.Produto')),
            ],
        ),
    ]
